import pytest
from unittest.mock import AsyncMock, MagicMock, patch
import os
from google.genai import types
from datetime import datetime
import asyncio # Import asyncio

# Adjust the import path for generate_images and config
# Assuming this test file is in backend/tests/
# and tools.py is in backend/agents/
# and config.py is in backend/agents/
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'agents')))

from agents.tools import generate_images
from agents import config

@pytest.fixture(autouse=True)
def mock_env_vars():
    """Mocks environment variables for the test."""
    with patch.dict(os.environ, {
        "GOOGLE_CLOUD_PROJECT": "test-project",
        "GCS_BUCKET_NAME": "test-bucket",
        "IMAGEN_MODEL": "imagen-3.0-generate-002",
        "GENAI_MODEL": "gemini-2.0-flash",
    }):
        yield

@pytest.mark.asyncio # Re-add this decorator
async def test_generate_images_success_no_gcs():
    """
    Tests successful image generation without GCS interaction.
    Mocks genai client to return a dummy image.
    """
    mock_image_bytes = b"dummy_image_content"
    mock_response = MagicMock()
    mock_response.generated_images = [MagicMock()]
    mock_response.generated_images[0].image.image_bytes = mock_image_bytes

    mock_genai_client = MagicMock()
    mock_genai_client.models.generate_images = AsyncMock(return_value=mock_response)

    mock_tool_context = MagicMock()
    mock_tool_context.state = {"loop_iteration": 1, "unique_id": "test-id"}
    mock_tool_context.save_artifact = AsyncMock()

    # Temporarily disable GCS_BUCKET_NAME for this test
    with patch.dict(os.environ, {"GCS_BUCKET_NAME": ""}):
        with patch('agents.tools.genai.Client', return_value=mock_genai_client), \
             patch('agents.tools.storage.Client') as mock_storage_client: # Ensure storage client is mocked
            
            result = await generate_images("a tranquil landscape", mock_tool_context)

            assert result["status"] == "success"
            assert "Image generated" in result["message"]
            assert "artifact_name" in result
            assert mock_tool_context.save_artifact.called
            assert mock_tool_context.state["image_url"] == "/generated_images/generated_image_1.png"
            mock_genai_client.models.generate_images.assert_called_once()
            mock_storage_client.assert_not_called() # GCS should not be called

@pytest.mark.asyncio # Re-add this decorator
async def test_generate_images_success_with_gcs():
    """
    Tests successful image generation with GCS interaction.
    Mocks genai client to return a dummy image and GCS client for upload.
    """
    mock_image_bytes = b"dummy_image_content_gcs"
    mock_response = MagicMock()
    mock_response.generated_images = [MagicMock()]
    mock_response.generated_images[0].image.image_bytes = mock_image_bytes

    mock_genai_client = MagicMock()
    mock_genai_client.models.generate_images = AsyncMock(return_value=mock_response)

    mock_tool_context = MagicMock()
    mock_tool_context.state = {"loop_iteration": 1, "unique_id": "test-id"}
    mock_tool_context.save_artifact = AsyncMock()

    # Mock GCS
    mock_blob = MagicMock()
    mock_bucket = MagicMock()
    mock_bucket.blob.return_value = mock_blob
    mock_storage_client = MagicMock()
    mock_storage_client.bucket.return_value = mock_bucket

    with patch('agents.tools.genai.Client', return_value=mock_genai_client), \
         patch('agents.tools.storage.Client', return_value=mock_storage_client):
        
        result = await generate_images("a tranquil landscape for gcs", mock_tool_context)

        assert result["status"] == "success"
        assert "Image generated" in result["message"]
        assert mock_tool_context.save_artifact.called
        assert "generated_image_gcs_uri_1" in mock_tool_context.state
        assert mock_tool_context.state["image_url"] == "/generated_images/generated_image_1.png"
        
        mock_genai_client.models.generate_images.assert_called_once()
        mock_storage_client.assert_called_once()
        mock_bucket.blob.assert_called_once()
        mock_blob.upload_from_string.assert_called_once_with(mock_image_bytes, content_type="image/png")

@pytest.mark.asyncio # Re-add this decorator
async def test_generate_images_no_image_returned():
    """
    Tests the scenario where the genai client returns no generated images.
    """
    mock_response = MagicMock()
    mock_response.generated_images = None # Simulate no images returned
    mock_response.error = "No images were generated by the model." # Simulate an error field

    mock_genai_client = MagicMock()
    mock_genai_client.models.generate_images = AsyncMock(return_value=mock_response)

    mock_tool_context = MagicMock()
    mock_tool_context.state = {}
    mock_tool_context.save_artifact = AsyncMock()

    with patch('agents.tools.genai.Client', return_value=mock_genai_client):
        result = await generate_images("a test prompt", mock_tool_context)

        assert result["status"] == "error"
        assert "No images generated" in result["message"]
        assert "No images were generated by the model." in result["message"]
        mock_tool_context.save_artifact.assert_not_called()

@pytest.mark.asyncio # Re-add this decorator
async def test_generate_images_exception_during_generation():
    """
    Tests error handling when an exception occurs during image generation.
    """
    mock_genai_client = MagicMock()
    mock_genai_client.models.generate_images = AsyncMock(side_effect=Exception("API error"))

    mock_tool_context = MagicMock()
    mock_tool_context.state = {}
    mock_tool_context.save_artifact = AsyncMock()

    with patch('agents.tools.genai.Client', return_value=mock_genai_client):
        result = await generate_images("a test prompt", mock_tool_context)

        assert result["status"] == "error"
        assert "Image generation failed: API error" in result["message"]
        mock_tool_context.save_artifact.assert_not_called()